### ISSUE TITLE
Add rule for defining inline static final arrays

### ISSUE THREAD

**Issue by sameer2086** [airlift/airbase#169]
Current building class with following code fails during style check:

```
private static final HiveColumnHandle[] DEFAULT_TEST_COLUMNS = { ARTICLE_COLUMN, AUTHOR_COLUMN, DATE_ARTICLE_COLUMN, QUANTITY_COLUMN };
```

Checkstyle error:
```
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ presto-hive ---
[INFO] There is 1 error reported by Checkstyle 8.7 with checkstyle/airbase-checks.xml ruleset.
[ERROR] src/test/java/com/facebook/presto/hive/TestS3SelectRecordCursor.java:[54,69] (whitespace) NoWhitespaceAfter: '{' is followed by whitespace.
```

This improvement was requested in https://github.com/prestodb/presto/pull/11970
```
nezihyigitbasi 20 hours ago  Contributor
nit: { ARTICLE_COLUMN, AUTHOR_COLUMN, DATE_ARTICLE_COLUMN, QUANTITY_COLUMN };

(Would be nice to have a checkstyle for this.)
```

**Comment by nezihyigitbasi** [comment]
Looks like there was an intentional recent change for array initializers' style (https://github.com/airlift/airbase/commit/6322fd3da65b2e7a8de9f50500ba8b5fd0f2c513), which is probably causing this.

**Comment by tdcmeehan** [comment]
The commit above was just a revert of #150 which only existed for a short while (because we found it didn't work as expected for two dimensional arrays), I don't think it's the cause of this.

**Comment by electrum** [comment]
The check was actually to enforce whitespace before the opening brace. Example of bad code:
```java
int[] abc ={123};
```
We actually don't want whitespace between the brace and the first item. (the comment from @nezihyigitbasi was incorrect per the code style)
